#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AplicacionSumaDineo.Resource", IsApplication=true)]

namespace AplicacionSumaDineo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int btnagregar1 = 2130968581;
			
			// aapt resource value: 0x7f040029
			public const int btnagregar10 = 2130968617;
			
			// aapt resource value: 0x7f04000b
			public const int btnagregar2 = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int btnagregar3 = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int btnagregar4 = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int btnagregar5 = 2130968605;
			
			// aapt resource value: 0x7f040023
			public const int btnagregar6 = 2130968611;
			
			// aapt resource value: 0x7f04002e
			public const int btnagregar7 = 2130968622;
			
			// aapt resource value: 0x7f040034
			public const int btnagregar8 = 2130968628;
			
			// aapt resource value: 0x7f04003a
			public const int btnagregar9 = 2130968634;
			
			// aapt resource value: 0x7f040006
			public const int btnrestar1 = 2130968582;
			
			// aapt resource value: 0x7f04002a
			public const int btnrestar10 = 2130968618;
			
			// aapt resource value: 0x7f04000c
			public const int btnrestar2 = 2130968588;
			
			// aapt resource value: 0x7f040012
			public const int btnrestar3 = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int btnrestar4 = 2130968600;
			
			// aapt resource value: 0x7f04001e
			public const int btnrestar5 = 2130968606;
			
			// aapt resource value: 0x7f040024
			public const int btnrestar6 = 2130968612;
			
			// aapt resource value: 0x7f04002f
			public const int btnrestar7 = 2130968623;
			
			// aapt resource value: 0x7f040035
			public const int btnrestar8 = 2130968629;
			
			// aapt resource value: 0x7f04003b
			public const int btnrestar9 = 2130968635;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040038
			public const int linearLayout10 = 2130968632;
			
			// aapt resource value: 0x7f040015
			public const int linearLayout11 = 2130968597;
			
			// aapt resource value: 0x7f040027
			public const int linearLayout12 = 2130968615;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout2 = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout3 = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int linearLayout4 = 2130968591;
			
			// aapt resource value: 0x7f04001b
			public const int linearLayout6 = 2130968603;
			
			// aapt resource value: 0x7f040021
			public const int linearLayout7 = 2130968609;
			
			// aapt resource value: 0x7f04002d
			public const int linearLayout8 = 2130968621;
			
			// aapt resource value: 0x7f040032
			public const int linearLayout9 = 2130968626;
			
			// aapt resource value: 0x7f040001
			public const int textView1 = 2130968577;
			
			// aapt resource value: 0x7f040039
			public const int textView10 = 2130968633;
			
			// aapt resource value: 0x7f040007
			public const int textView11 = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int textView12 = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int textView13 = 2130968595;
			
			// aapt resource value: 0x7f040019
			public const int textView14 = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int textView15 = 2130968607;
			
			// aapt resource value: 0x7f040025
			public const int textView16 = 2130968613;
			
			// aapt resource value: 0x7f04002b
			public const int textView17 = 2130968619;
			
			// aapt resource value: 0x7f040030
			public const int textView18 = 2130968624;
			
			// aapt resource value: 0x7f040036
			public const int textView19 = 2130968630;
			
			// aapt resource value: 0x7f040004
			public const int textView2 = 2130968580;
			
			// aapt resource value: 0x7f04003c
			public const int textView20 = 2130968636;
			
			// aapt resource value: 0x7f04000a
			public const int textView3 = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int textView4 = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int textView5 = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int textView6 = 2130968604;
			
			// aapt resource value: 0x7f040022
			public const int textView7 = 2130968610;
			
			// aapt resource value: 0x7f040028
			public const int textView8 = 2130968616;
			
			// aapt resource value: 0x7f040033
			public const int textView9 = 2130968627;
			
			// aapt resource value: 0x7f040002
			public const int txt_cantidad = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int txtcantidad1 = 2130968584;
			
			// aapt resource value: 0x7f04002c
			public const int txtcantidad10 = 2130968620;
			
			// aapt resource value: 0x7f04000e
			public const int txtcantidad2 = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int txtcantidad3 = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int txtcantidad4 = 2130968602;
			
			// aapt resource value: 0x7f040020
			public const int txtcantidad5 = 2130968608;
			
			// aapt resource value: 0x7f040026
			public const int txtcantidad6 = 2130968614;
			
			// aapt resource value: 0x7f040031
			public const int txtcantidad7 = 2130968625;
			
			// aapt resource value: 0x7f040037
			public const int txtcantidad8 = 2130968631;
			
			// aapt resource value: 0x7f04003d
			public const int txtcantidad9 = 2130968637;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
